package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hello.idl
* Monday, February 19, 2018 9:26:23 PM CET
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
